version: "3.8"

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - localstack
    environment:
      BASE_URL: http://flask-api:5000
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      DYNAMODB_ENDPOINT_URL: http://localstack:4566
      S3_ENDPOINT_URL: http://localstack:4566
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  flask-api-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      flask-api:
        condition: service_healthy

    environment:
      BASE_URL: http://flask-api:5000
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      DYNAMODB_ENDPOINT_URL: http://localstack:4566
      S3_ENDPOINT_URL: http://localstack:4566

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=0
    ports:
      - "4566:4566"