version: "3.8"

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - localstack
    environment:
      BASE_URL: http://flask-api:5000
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      DYNAMODB_ENDPOINT_URL: http://localstack:4566
      S3_ENDPOINT_URL: http://localstack:4566

  flask-api-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - flask-api
    environment:
      BASE_URL: http://flask-api:5000
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      DYNAMODB_ENDPOINT_URL: http://localstack:4566
      S3_ENDPOINT_URL: http://localstack:4566

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
    ports:
      - "4566:4566"