# Runs tests via test.sh shell script

name: Python application

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Make scripts executable
      run: chmod +x test.sh

    - name: Run test shell script (docker-compose.test.yml -> Dockerfile and Dockerfile.test)
      run: ./test.sh
